config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :cats, :except =>[:new,:edit,:destroy] do
    member do
      post :vote
    end
    collection do
      get :top
      get :fight
    end
  end

  root 'cats#fight'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
	extend CatHunter
	has_many :votes, dependent: :delete_all
	validates :thumb_image_of_the_cat, uniqueness: true 

	def self.top_cats(limit = 10, date = "2000-01-01")
		Cat.where(id: get_cats(limit,date)).order(cuteness_score: :desc)
	end

	def self.get_cats(limit = 10, date = "2000-01-01")
		#Vote.select(:cat_id).according_to_date(date).group(:cat_id).limit(limit).count.keys
		Vote.according_to_date(date).group(:cat_id).limit(limit).count.keys
	end

	def self.get_random_cats(limit = 2)
		Cat.where(id: Cat.ids.sort_by {rand}.slice(0,limit))
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :cat, counter_cache: :cuteness_score

	scope :according_to_date, ->(date = "2000-01-01") { where("created_at >=?",date) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #rescue_from ActiveRecord::RecordNotFound, :with => :rescue404
  #rescue_from ActionController::RoutingError, :with => :rescue404

  def rescue_404
  	render plain: "this cat does not exist"
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  

  # GET /cats
  # GET /cats.json
  def index
    if current_user.admin?
      @cats = Cat.paginate(page: params[:page], per_page: 20).order(cuteness_score: :desc)
    else
      redirect_to action: :fight and return
    end
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  def top    
    @cats = Cat.top_cats(10,params[:custom_date])      
  end

  def fight
    tmp = Cat.get_random_cats(2)
    @cat_1 = tmp[0]
    @cat_2 = tmp[1]
  end
  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.json { render :show, status: :ok}
        format.html { redirect_to fight_path, notice: 'Cat was successfully updated.' }
      else
        format.json { render json: @cat.errors, status: :unprocessable_entity }
        format.html { render :edit }
        
      end
    end
  end

  def vote
    #byebug
    @cat = Cat.find(params[:id])
    @cat.votes << Vote.create
    #@cat.increment!(:cuteness_score)
    redirect_to action: :fight
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params[:cat]
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_cat.html.erb
<div>
    <div class="col-xs-12">
        <div class="panel panel-defult">
            <div class="panel-body">
                <%= image_tag cat.thumb_image_of_the_cat, class: "img-thumbnail img-responsive" %>
            </div>
            <div class="panel-footer">
                Score: <%= cat.cuteness_score %>
            </div>  
        </div>
    </div>
</div>

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
<% if @cat.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

  <ul>
    <% @cat.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/cats/fight.html.erb
<div class="container" id="images-of-cat">
	<div class="row">
		<div class="col-lg-6 col-sm-5 col-xs-12 fixed">
			<div class="panel panel-defult">
				<div class="panel-body">
					<%= image_tag @cat_1.thumb_image_of_the_cat, class: "img-thumbnail img-responsive" %>
				</div>
				<div class="panel-footer">
					<%= button_to [:vote, @cat_1], id: "cat_1" do %>
					Vote on me! <%= @cat_1.cuteness_score %>
					<% end %>
				</div> 	
			</div>
		</div>
		<div class="col-lg-6 col-sm-5 col-xs-12">
			<div class="panel panel-defult">
				<div class="panel-body">
					<%= image_tag @cat_2.thumb_image_of_the_cat, class: "img-thumbnail img-responsive" %>
				</div>
				<div class="panel-footer">
					<%= button_to [:vote, @cat_2], id: "cat_2" do %>
					Vote on me! <%= @cat_2.cuteness_score %>
					<% end %>
				</div> 	
			</div>
		</div>
	</div>
</div>

app/views/cats/index.html.erb
<div class="page-header">
  <h1> Cats! </h1>
</div>

<div id="kitties">
  <%= render @cats %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate %>
</div>

app/views/cats/index.js.erb
$('#kitties').append('<%= j render @cats %>');
<% if @cats.next_page %>
$('.pagination').replaceWith('<%= j will_paginate @cats %>');
<% else %>
$(window).off('scroll');
$('.pagination').remove();
<% end %>

app/views/cats/top.html.erb
<div class="page-header">
  <h1> Top Cats! </h1>
</div>
<div id="kitties">
  <%= render @cats %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cat Fight Club</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= render 'shared/header' %>
      </div>
    </div>
    <div class="row">    
      <div class="col-md-2">	
        <%= render 'shared/sidebar' %>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/shared/_header.html.erb
 <div class="row">
  <div class="col-md-offset-2 col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading text-center">
       
      
      <div class="panel-body">
       ! FIGHT ! ! FIGHT ! ! FIGHT ! ! FIGHT ! ! FIGHT ! ! FIGHT ! ! FIGHT ! ! FIGHT ! ! FIGHT ! ! FIGHT !
      </div>
      </div>
     </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Cats", fight_cats_path, class: "navbar-brand" %>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <% if   user_signed_in? %>
    <ul class="nav navbar-nav">
      <li><%= link_to "Top cats of the day"  , top_cats_path(custom_date: Date.today)    %></li>
      <li><%= link_to "Top cats of the week" , top_cats_path(custom_date: Date.today-7)  %></li>
      <li><%= link_to "Top cats of the month", top_cats_path(custom_date: Date.today-30) %></li>
      <li><%= link_to "Top cats of all time" , top_cats_path                %></li>
      <% if current_user.admin? %>

      <li><%= link_to "only for admins", cats_path %></li>
      <% end %>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    </ul>
    <% end %>
  </div>
</nav>